### ISSUE TITLE
Improved class registration

### ISSUE THREAD

**Issue by ekaj2** [blendfx/blender#1]
To simplify class registration, try something like this:

```
classes = (ClassA, ClassB, ClassC)

def register():
    for i in classes:
        register_class(i)

def unregister():
    for i in classes:
        unregister_class(i)

```

Of course, to do it this way, you'd need to import:

`from bpy.utils import register_class, unregister_class`

**Comment by blendfx** [comment]
Thanks for the suggestion, implemented in r51fb9ae.
